name: Lean Action CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Lean
        uses: leanprover/lean-action@v1
        with:
          use-toolchain-file: true

      - name: Cache Lake dependencies
        uses: actions/cache@v3
        with:
          path: ./.lake/packages
          key: ${{ runner.os }}-lean-${{ hashFiles('**/lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lean-

      - name: Build and Run Tests
        run: lake exe tests
